image:
  file: .gitpod.Dockerfile

tasks:
  - init: pip install -r requirements.txt  # Install dependencies
  - command: flask run --host=0.0.0.0  # Run the Flask app

ports:
  - port: 5000  # Open port 5000 for Flask
    onOpen: open-browser  # Automatically open the browser on port 5000
