image:
  file: .gitpod.Dockerfile   # Pointing to the custom Dockerfile

tasks:
  - command: |
      pip install -r requirements.txt   # Install dependencies if not already done
      python train.py                   # Run the training script
