image:
  file: .gitpod.Dockerfile   # Pointing to the custom Dockerfile

tasks:
  - command: |
      pip install -r requirements.txt  # Install the dependencies
      python train.py                  # Run your training script
