# Configuration settings for the app

flask:
  host: "0.0.0.0"
  port: 5000

model:
  name: "YourModelName"
  version: "1.0"

logging:
  level: "INFO"
  file: "app.log"

# Timezone (already set in Dockerfile, but can be useful for logs)
timezone: "America/New_York"
