meta_learning:
  inner_lr: 0.01   # Learning rate for the inner loop (task-specific updates)
  meta_lr: 0.001   # Learning rate for the outer loop (meta-update)
  epochs: 5        # Number of epochs for training
